### ISSUE TITLE
add the initial style from openingElement style

### ISSUE THREAD

**Issue by ycjcl868** [ycjcl868/jsx2css#2]
```jsx
<div className="hello" style={{ fontSize: '12px' }}>
</div>
```

=>

```css
.hello { 
  font-size: 12px;
}
```
